# TODO: test condor
language: python
dist: bionic
matrix:
  include:
  - python: 3.7
    env: TOX_ENV=py37-lint-dist
  - python: 3.7
    env: TOX_ENV=lint-docs
  - python: 3.5
    env: TOX_ENV=py35-lint
  - python: 3.5
    env: TOX_ENV=py35 SETUP=true
  - python: 3.5
    env: TOX_ENV=py35-unit SETUP=true
  - python: 3.6
    env: TOX_ENV=py36 SETUP=true
  - python: 3.6
    env: TOX_ENV=py36-unit SETUP=true
  - python: 3.7
    env: TOX_ENV=py37 SETUP=true
  - python: 3.7
    env: TOX_ENV=py37-unit SETUP=true
  - python: 3.7
    env:  TOX_ENV=py37-install-wheel

install:
  - pip install tox
  - if [ "$SETUP" == "true" ]; then .travis/setup_tests.sh; fi

script: export PULSAR_TEST_KEY=test_data/testkey; export TEST_WEBAPP_POST_SHUTDOWN_SLEEP=1; . local_env.sh; tox -e $TOX_ENV

after_success:
  - coveralls
